name: Test
on: push
jobs:
  test_python:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        cache: 'pip'
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        python setup.py develop

    - name: Run the Testsuite
      run: |
        python -m pytest
