name: Test
on: push
jobs:
  test_python:
    name: Python Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
        python setup.py develop

    - name: Run the Testsuite
      run: |
        python -m pytest --verbose

  lint_python:
    name: Lint Pyton files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        pip install flake8

    - name: Run flake8
      run: |
        flake8 . --count --max-complexity=20 --max-line-length=120 --statistics --exclude venv
